version: '3'

services:
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${RDS_ENDPOINT}
      PMA_ARBITRARY: 1 # Allows to connection to any server

  wordpress:
    image: wordpress:6.6
    restart: always
    ports:
      - "9000:80"
    environment:
      WORDPRESS_DB_HOST: ${RDS_ENDPOINT}
      WORDPRESS_DB_USER: ${RDS_USERNAME}
      WORDPRESS_DB_PASSWORD: ${RDS_PASSWORD}
      WORDPRESS_DB_NAME: ${RDS_DB_NAME}
    volumes:
      - /mnt/efs/${VOLUME_NAME}:/var/www/html
  wordpress-cli:
    restart: on-failure
    image: wordpress:cli-2.10
    environment:
      WORDPRESS_DB_HOST: ${RDS_ENDPOINT}
      WORDPRESS_DB_USER: ${RDS_USERNAME}
      WORDPRESS_DB_PASSWORD: ${RDS_PASSWORD}
      WORDPRESS_DB_NAME: ${RDS_DB_NAME}
    command: >
      /bin/sh -c '
      wp core install --path="/var/www/html" --url=${WP_URL} --title=${WP_TITLE} --admin_user=${WP_ADMIN_USER} --admin_password=${WP_ADMIN_PASSWORD} --admin_email=${WP_ADMIN_EMAIL}
      '
    volumes:
      - /mnt/efs/${VOLUME_NAME}:/var/www/html
